-- USERS TABLE
create table users (
    id uuid references auth.users(id) primary key,
    name text,
    mssv text,
    email text,
    phone text,
    birth_year int4,
    is_tutor boolean default false,
    verified boolean default false,
    subjects_can_teach text
);

-- MESSAGES TABLE
create table messages (
    id int8 generated by default as identity primary key,
    sender_id uuid references users(id) on delete cascade,
    receiver_id uuid references users(id) on delete cascade,
    content text,
    created_at timestamptz default now()
);

-- STUDY BUDDY REQUESTS TABLE
create table study_buddy_requests (
    id int8 generated by default as identity primary key,
    user_id uuid references users(id) on delete cascade,
    number_of_people int4,
    subject_id text,
    mode text check (mode in ('online','offline')),
    link_or_address text,
    time text,
    note text,
    status text default 'open'
);

-- TUTOR REQUESTS TABLE
create table tutor_requests (
    id int8 generated by default as identity primary key,
    user_id uuid references users(id) on delete cascade,
    subject_id text,
    mode text check (mode in ('online','offline')),
    link_or_address text,
    time text,
    note text,
    status text default 'open'
);

-- NOTIFICATIONS TABLE
create table notifications (
    id int8 generated by default as identity primary key,
    user_id uuid references users(id) on delete cascade,
    content text,
    is_read boolean default false,
    created_at timestamptz default now()
);